{% set name = "PIMS" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aa2f6143878bdca555960ca673a2ff27014260aab97a93b3ac3cbda58ac702a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - slicerator >=0.9.7
    - six >=1.8
    - numpy >=1.7
# The following dependencies are only required for rich IPython display
    - jinja2
    - pillow
# The following dependencies are optional (for specific readers)
    - scipy  # one of { scikit-image | matplotlib | scipy }
    - tifffile

test:
  imports:
    - pims
    - pims.api
    - pims.base_frames
    - pims.bioformats
    - pims.cine
    - pims.display
    - pims.ffmpeg_reader
    - pims.frame
    - pims.image_reader
    - pims.image_sequence
    - pims.imageio_reader
    - pims.moviepy_reader
    - pims.norpix_reader
    - pims.pyav_reader
    - pims.spe_stack
    - pims.tiff_stack
    - pims.tests
    - pims.utils
    - pims.utils.misc
    - pims.utils.sort

about:
  home: https://github.com/soft-matter/pims
  license: BSD 3-Clause
  license_file: license.txt
  summary: >
      Python Image Sequence. Load video and sequential images in many formats 
      with a simple, consistent interface.

extra:
  recipe-maintainers:
    - danielballan
    - ericdill
    - jakirkham
    - licode
    - tacaswell
    - caspervdw
    - nkeim
