{% set name = "PIMS" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a02cdcbb153e2792042fb0bae7df4f30878bbba1f2d176114a87ee0dc18715a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - slicerator >=0.9.7
    - six >=1.8
    - numpy >=1.7
# The following dependencies are only required for rich IPython display
    - jinja2
    - pillow
# The following dependencies are optional (for specific readers)
    - matplotlib  # one of { scikit-image | matplotlib }
    - tifffile

test:
  imports:
    - pims
    - pims.api
    - pims.base_frames
    - pims.bioformats
    - pims.cine
    - pims.display
    - pims.ffmpeg_reader
    - pims.frame
    - pims.image_reader
    - pims.image_sequence
    - pims.imageio_reader
    - pims.moviepy_reader
    - pims.norpix_reader
    - pims.pyav_reader
    - pims.spe_stack
    - pims.tiff_stack
    - pims.tests
    - pims.utils
    - pims.utils.misc
    - pims.utils.sort

about:
  home: https://github.com/soft-matter/pims
  license: BSD-3-Clause
  license_file: license.txt
  summary: >
    Python Image Sequence. Load video and sequential images in many formats with a simple, consistent interface.

extra:
  recipe-maintainers:
    - danielballan
    - ericdill
    - jakirkham
    - tacaswell
    - caspervdw
    - nkeim
